### ISSUE TITLE
TBS6032: clarification on initialization and userspace data transmission

### ISSUE THREAD

**Issue by door** [tbsdtv/linux_media#414]
#### TL;DR: 
When streaming to a TBS6032 device, the userspace program hangs on a system call (likely `write` or `ioctl`). We would like clarification on correct initialization, userspace transmission, and bitrate setup.

#### Issue description

We are trying to start transmission on a TBS6032 device.

Before starting the transmission, initialization is performed by running `./GenSpiCmd -a 0 -b 0 -M -Q 256 -s 5`.
After that, data is written to `/dev/tbsmod0/mod0` with a **constant bitrate** stream.
Shortly after the transmission starts, we begin to see driver errors `tbsmod_write buffer fulled`.
The higher the bitrate, the sooner this error appears.
At the moment, it is unclear what we are missing in terms of configuration, pacing, or driver expectations.

#### Driver version (released build)

The driver was installed by running `./build` from the official media_build package.
The issue described above (tbsmod_write buffer fulled) occurs with this version.

#### Driver version (latest Git)

When trying to use the latest driver version from Git, the behavior changes.
At the very beginning of transmission, the kernel reports a divide-by-zero error:
```
bitrate: 0 
empty_packet_size: 2 
divide error: 0000 [#1] PREEMPT SMP NOPTI
```

This suggests that the device may not have been fully or correctly initialized before transmission starts.

System information
    * OS: Ubuntu 24.04
    * Kernel: 6.8.0-31-generic
    * Hardware: TBS6032

#### Question
Are there recommended userspace steps, pacing, or configuration needed to properly initialize the device and stream data to /dev/tbsmod0/mod0?

Any guidance on the correct transmission workflow for this device would be greatly appreciated.

**Comment by daowei23tbs-coder** [comment]
Hi,
This comes from TBS support team.

For "qam configuration", we suggest to use a complete command line, like this:
# ./GenSpiCmd -a 0 -b 0 -M -N 16 -T 16 -A -Q 256 -F 534e6 -D -s 5.36 -f 032DA16_5862_4608M_300M_32Slot_5360SymR.txt

And, about the "buffer full" issue, i guess  you're using an older firmware for your Modualtor. We have a newer firmware now and this issue has been fixed. Please check your Modulator firmware and send it to us. Here's the firmware tool
https://www.tbsdtv.com/tmp/v3/tbs6032-fpga.tar.bz2 

# ./6032-fpga    -a 0   -v

if the Binary is not working in your system,  just compile again, source code in "/src"
# gcc   -o     "tool-xxx"  *.c

Thanks

**Comment by door** [comment]
Hi, thank you for your response! 

```
# ./6032-fpga -a 0 -v
ID:0xc2
ID:0x20
ID:0x18
version:0x20
version:0x24
version:0x8
version:0x23
FW Version : 0x 823
```

**Comment by daowei23tbs-coder** [comment]
Hi door,
Ok, thanks for your update.

Your tbs6032 is using an older firmware (v-20240823 is) now, needs to update. Can you setup ssh? then , we can upgrade firmware. Or, give your e-mail to me, i'll send new firmware to you separately.

By the way, what about the software of Modulator card now? it's our Kylone  or your own software?

Thanks

**Comment by door** [comment]
Hi!

Please send it to [redacted]

> By the way, what about the software of Modulator card now? it's our Kylone or your own software?

So far, we haven’t been able to get it running yet. We’re focusing on using the hardware through the linux driver API. Thank you for your assistance!

**Comment by daowei23tbs-coder** [comment]
Hi door,
Done.
Already sent by e-mail, please check.

Thanks

**Comment by door** [comment]
Hi!

We have installed the firmware update, and the “buffer fulled” error has disappeared.
However, the connected TV still does not receive a signal. We will continue investigating the issue and will keep you informed.

Thank you very much for your help and support — we really appreciate it.


```
# ./6032-fpga -a 0 -w ./tbs6032_25061802.bin
ID:0xc2
ID:0x20
ID:0x18
version:0x20
version:0x24
version:0x8
version:0x23
FW Version : 0x 823
start writing flash.
write file len=4456100
File read Over!!!
write flash finish.
File Open successed.
read file len=4456100
read flash successed.
flash update OK
```

After a power cycle, the firmware version has changed:

```
# ./6032-fpga -a 0 -v
ID:0xc2
ID:0x20
ID:0x18
version:0x25
version:0x6
version:0x18
version:0x2
FW Version : 0x18 2
```

**Comment by daowei23tbs-coder** [comment]
Hi door,
I guess maybe something wrong with your application, we can give you a demo application (remux) to test, it's to receive IP streams &  write to modulator "/dev/tbsmod0/modxx":
https://www.tbsdtv.com/tmp/v3/tbs6032/remux_demo.tar.bz2

1. QAM config:
# ./GenSpiCmd -a 0 -b 0 -M -N 16 -T 16 -A -Q 256 -F 534e6 -D -s 6.9 -f 032DA16_5862_4608M_300M_32Slot_5360SymR.txt
the first Frequency is 474Mhz, Symbol rate: 6.9Msyms/s, 256-QAM
Frequency informations, please check "032DA16_5862_4608M_300M_32Slot_5360SymR.txt" line 223~line 238

2.
Prepare IP streams (for example, udp, http), and configure stream URLs to remux configuration file "remux_channels.conf "

3.
run remux cmd line & start to modulate
# ./remux -C -a 0 -A 0 -B 48 -c remux_channels.conf -g remux.conf -n remux_nit.conf
(if Binary "remux" does not work in your linux system, please let me know)
（-a 0 -A 0 means "/dev/tbsmod0/mod0"）

Thanks
